### ISSUE TITLE
Upnpx slow on SSDP discover, or ignoring SSDP discover replies

### ISSUE THREAD

**Issue by rworne** [fkuehne/upnpx#28]
I noticed this in the latest upnpx in this fork. When using it in my code and also with the included sample, devices responding to SSDP discover packets do not show up. They do show up after a couple minutes when a notify is received or possibly a stalled discover response is finally processed. I've stepped through the code and upnpx sees the replies, but the notification to the observer never seems to go out.

The discovery packets and responses were verified with Wireshark.

Other forks of upnpx do not show this problem.  This happens on both a native iOS device and in the simulator in iOS 7.  If there's something specific you need from me to trace this, let me know.

**Comment by lightbow** [comment]
I'm also having trouble getting upnpx to do discovery. If I use another tool like miranda.py my three upnp devices show up right away, but with upnpx, I'm often not seeing anything get back to the observer.

**Comment by rworne** [comment]
It appears the devices all respond immediately and upnpx sees them, but I'm getting nothing in the list.  If other people are not having problems with it, it may be that some device is messing up upnpx's parser with some non-standard reply.  All I see appear are devices that send out the periodic notify messages and it takes up to 5-6 minutes for most (but not all) devices to appear.

**Comment by lightbow** [comment]
I'm working with Belkin WeMo devices, so it wouldn't be too surprising if they were sending back nonstandard replies. Still, I would expect at least an error, or some report that a parsing job failed. Any tips on how to troubleshoot?

**Comment by rworne** [comment]
None that I can see.  It's been reported and I turned on and included debug messages above.

The devices are being seen - and parsed.  After that, I have no idea what happens.

**Comment by squarefrog** [comment]
@rworne @lightbow can you try this with the latest patch and see if that helps any?

I've had a possibly related issue where I know a renderer is sending events (verified with Intel tools Device Spy),  yet they never seem to appear to be picked up by upnpx. I've dropped down as low as I can go save for jumping to to C++ code.

**Comment by squarefrog** [comment]
Also if this issue is repeatable with certain UPnP devices please list them!

**Comment by rworne** [comment]
I'll test tonight. The problem is I have no idea if a device is causing this. 

Before with older forks, I got a notification every time a device was discovered. In your fork, I'll have 0 devices, get a notification, then I suddenly have 9 in my list. 

Robert W

**Comment by squarefrog** [comment]
Ah I think I know what you mean. Before you got individual notifications but now you just get them all grouped together?

Do you have a link to a fork that does not exhibit this behaviour?

**Comment by rworne** [comment]
The old upnpx did this, but it just worked "better" I cannot say it worked perfectly. 

I cannot use it anymore because it just crashes with iOS8

**Comment by rworne** [comment]
No need.

I just ran the new version and it is fast as hell.

FOUND thisaddress->ifa_name:en0
2015-01-23 17:18:40.228 upnpxdemo[14493:177351] UPnPDBWillUpdate 0
2015-01-23 17:18:40.697 upnpxdemo[14493:177351] UPnPDBUpdated 13
2015-01-23 17:18:40.698 upnpxdemo[14493:177280] 0 Netgear R6300V2:DD-WRT
2015-01-23 17:18:40.699 upnpxdemo[14493:177280] 1 WANDevice
2015-01-23 17:18:40.700 upnpxdemo[14493:177280] 2 ReadyNAS: ReadyNAS NV+
2015-01-23 17:18:40.700 upnpxdemo[14493:177280] 3 WAN Connection Device
2015-01-23 17:18:40.701 upnpxdemo[14493:177280] 4 LANDevice
2015-01-23 17:18:40.701 upnpxdemo[14493:177280] 5 Kodi (HTPC)
2015-01-23 17:18:40.702 upnpxdemo[14493:177280] 6 TOUCHY: CaCa:
2015-01-23 17:18:40.702 upnpxdemo[14493:177280] 7 TX-NR609
2015-01-23 17:18:40.702 upnpxdemo[14493:177280] 8 CR-N755
2015-01-23 17:18:40.703 upnpxdemo[14493:177280] 9 TX-NR708
2015-01-23 17:18:40.703 upnpxdemo[14493:177280] 10 RX-V775
2015-01-23 17:18:43.745 upnpxdemo[14493:177280] 11 Kodi (HTPC)
2015-01-23 17:18:43.796 upnpxdemo[14493:177280] 12 ViP222 Dish R0084531923
2015-01-23 17:18:44.617 upnpxdemo[14493:177280] 2 ReadyNAS: ReadyNAS NV+

Detection of all these was less than 1 second.  Great job!  I’ll have to work with it a bit to be absolutely sure - I also turned on and off devices and they were added/removed OK too.

Robert W.

**Comment by squarefrog** [comment]
I'm starting to get reports of this happening to users (my companies sales reps) in the field. I'm at a loss as to why this is happening as I use similar NAS drives in my dev setup and it works fine. 

The same network using a different app (e.g. PlugPlayer) and the devices show up within 4 seconds. I think this issue could do with being reopened.

**Comment by rworne** [comment]
Are you using the latest revision?

This problem disappeared over the last two or three. Works much better for me now.

**Comment by squarefrog** [comment]
Yes this is on the latest release. I'm unable to reproduce locally, so my chances of fixing this are pretty slim.

**Comment by rworne** [comment]
What I’ve found out is when doing the initial search, you can send out the search several times:

    //Search for UPnP Devices 
    [[[UPnPManager GetInstance] SSDP] searchSSDP];
    [[[UPnPManager GetInstance] SSDP] searchSSDP];
    [[[UPnPManager GetInstance] SSDP] searchSSDP];

Just repeat the searchSSDP call (or whichever of the search methods you use) 2 or 3x and detection will speed up.

I’ve also noticed with UDP broadcasts that poor WiFi areas will cause response packets to be lost.  This also increases your chances of a response coming back in iffy situations.

**Comment by squarefrog** [comment]
Yes I don't think that's a bad solution, considering were waiting for a simple fire-and-forget packet, it's highly probably that the replies are just lost in transit. 

Personally I have a timer that searches every 10 seconds, which is fine. 

I presume this is the issue, rather than an problem with parser code.

**Comment by murthysaini** [comment]
I am using the latest version still my App has same issue. Sometimes its taking 6mins to list down my last UPnP Device. Please advise on correct version to be used(if possible please share the link).

Thanks in advance.

**Comment by alfredo-dslv** [comment]
I am also using the latest version off this library and I still cannot get all of my UPnP devices listed. Is there an actual fix for this problem?

Thanks.
