### ISSUE TITLE
Unable to build with iOS 8 & 7 as deployment target

### ISSUE THREAD

**Issue by ivan-konov** [fkuehne/upnpx#31]
If I set the deployment target for the demo project to 7 or 8 I get a lot of errors concerning the C++ files.

"Undefined symbols for architecture i386:
  "std::string::find(char const_, unsigned long) const", referenced from:
      SSDPNotifyAlive::Process(sockaddr_, std::vector<SSDP_HTTP_HEADER*, std::allocator<SSDP_HTTP_HEADER*> >) in libupnpx.a(ssdpnotifyalive.o)
      SSDPSearchResp::Process(sockaddr_, std::vector<SSDP_HTTP_HEADER_, std::allocator<SSDP_HTTP_HEADER*> >) in libupnpx.a(ssdpsearchresp.o)
  "std::string::c_str() const", referenced from:
"

And I have deleted i386 and 64_x86 as valid architectures from the library project

**Comment by incipio-srinu** [comment]
Getting red mark at libupnpx.a library file in Xcode project
