### ISSUE TITLE
Infinite loop on socketserver.cpp ReadLoop

### ISSUE THREAD

**Issue by mikyl** [fkuehne/upnpx#40]
I'm using version 1.3.0 of upnpx to play content from a Twonky server to an xbmc raspberry pi through an ios app. I got problem at the very beginning of the play to sequence (listing renderer & subscribe to avtransportservice). 
It appears that the select() of the socketServer::Readloop method never get clean FDS for the write events (writeFDS are not handled), causing the while to loop on select() and the thread to go 100% CPU. 

Adding this code to socketserver.cpp looks to clean write connections. 
349,350d347
<                 }else if(FD_ISSET(thisSocket, &mWriteFDS)){
<                     connection->isActive = false;

**Comment by fkuehne** [comment]
Can you provide a proper patch or even fork & merge request please?

**Comment by mikyl** [comment]
Ok, I have made a request.

**Comment by fkuehne** [comment]
Thanks! Merged!
