### ISSUE TITLE
Update Tag

### ISSUE THREAD

**Issue by squarefrog** [fkuehne/upnpx#44]
@fkuehne fancy bumping the tag to 1.3.1 and I'll update the pod?

    git tag 1.3.1
    git push --tags

**Comment by fkuehne** [comment]
Sure, but maybe we want to fix #28 first?

**Comment by squarefrog** [comment]
I think that wouldn't be a bad thing, but I have no idea how to approach it. I'll put a comment in there see if we can bump it.

**Comment by rworne** [comment]
#28 is fixed.

**Comment by fkuehne** [comment]
Indeed. Release tagged :)
