### ISSUE TITLE
UPnP observer not informed of events

### ISSUE THREAD

**Issue by squarefrog** [fkuehne/upnpx#46]
I have an issue with a particular renderer, where 90% of the time it's events fail to parse. I can see the events coming in through `basichttpserver.cpp`, but [this method](https://github.com/fkuehne/upnpx/blob/9e23c1c1d218e174f403e829f569007e7908c905/src/eventserver/basichttpserver.cpp#L116-L134) seems to be causing an issue:

    ret = thisSession->AddData(buf, (unsigned int)len);

On this particular renderer I never seem to get a `0` return value, so observer inform code is never called.

    (lldb) p ret
    (int) $3 = 2294
    (lldb) 

@fkuehne any suggestions where to start debugging this? I don't know C++ so I'm just poking at things and seeing what sticks!

**Comment by squarefrog** [comment]
The only difference I can see between a working renderer and non-working renderer is the length of the event payload.

## Renderer that sends events upnpx can parse

    <Event xmlns="urn:schemas-upnp-org:metadata-1-0/AVT/">
      <InstanceID val="0">
        <TransportState val="TRANSITIONING"/>
        <CurrentTrackDuration val="0:00:00.000"/>
      </InstanceID>
    </Event>

## Renderer that sends events upnpx cannot parse

    <Event xmlns="urn:schemas-upnp-org:metadata-1-0/AVT/">
      <InstanceID val="0">
        <PlaybackStorageMedium val="NETWORK"/>
        <TransportState val="TRANSITIONING"/>
        <CurrentTransportActions val="Stop"/>
        <AVTransportURI val="http://10.54.6.186:50002/m/NDLNA/3546.mp3"/>
        <CurrentTrackURI val="http://10.54.6.186:50002/m/NDLNA/3546.mp3"/>
        <NumberOfTracks val="1"/>
        <CurrentMediaDuration val="0:00:35.000"/>
        <CurrentTrackDuration val="0:00:35.000"/>
        <CurrentTrack val="1"/>
        <CurrentTrackMetaData val="&lt;?xml version=&quot;1.0&quot;?&gt;&lt;DIDL-Lite xmlns:dc=&quot;http://purl.org/dc/elements/1.1/&quot; xmlns:upnp=&quot;urn:schemas-upnp-org:metadata-1-0/upnp/&quot; xmlns=&quot;urn:schemas-upnp-org:metadata-1-0/DIDL-Lite/&quot; xmlns:dlna=&quot;urn:schemas-dlna-org:metadata-1-0/&quot;&gt;&lt;item id=&quot;26$3538$@3546&quot; parentID=&quot;26$3538&quot; restricted=&quot;1&quot;&gt;&lt;dc:title&gt;Transmission 1&lt;/dc:title&gt;&lt;upnp:class&gt;object.item.audioItem.musicTrack&lt;/upnp:class&gt;&lt;res protocolInfo=&quot;http-get:*:audio/mpeg:*&quot; size=&quot;919479&quot; duration=&quot;0:00:35.000&quot;&gt;http://10.54.6.186:50002/m/NDLNA/3546.mp3&lt;/res&gt;&lt;upnp:genre&gt;Electronic&lt;/upnp:genre&gt;&lt;upnp:artist&gt;DJ Shadow&lt;/upnp:artist&gt;&lt;dc:creator&gt;DJ Shadow&lt;/dc:creator&gt;&lt;upnp:album&gt;Endtroducing.....&lt;/upnp:album&gt;&lt;upnp:albumArtURI&gt;http://10.54.6.186:50002/transcoder/jpegtnscaler.cgi/ebdart/3546.jpg&lt;/upnp:albumArtURI&gt;&lt;dc:date&gt;1996-01-01&lt;/dc:date&gt;&lt;/item&gt;&lt;/DIDL-Lite&gt;"/>
        <AVTransportURIMetaData val="&lt;?xml version=&quot;1.0&quot;?&gt;&lt;DIDL-Lite xmlns:dc=&quot;http://purl.org/dc/elements/1.1/&quot; xmlns:upnp=&quot;urn:schemas-upnp-org:metadata-1-0/upnp/&quot; xmlns=&quot;urn:schemas-upnp-org:metadata-1-0/DIDL-Lite/&quot; xmlns:dlna=&quot;urn:schemas-dlna-org:metadata-1-0/&quot;&gt;&lt;item id=&quot;26$3538$@3546&quot; parentID=&quot;26$3538&quot; restricted=&quot;1&quot;&gt;&lt;dc:title&gt;Transmission 1&lt;/dc:title&gt;&lt;upnp:class&gt;object.item.audioItem.musicTrack&lt;/upnp:class&gt;&lt;res protocolInfo=&quot;http-get:*:audio/mpeg:*&quot; size=&quot;919479&quot; duration=&quot;0:00:35.000&quot;&gt;http://10.54.6.186:50002/m/NDLNA/3546.mp3&lt;/res&gt;&lt;upnp:genre&gt;Electronic&lt;/upnp:genre&gt;&lt;upnp:artist&gt;DJ Shadow&lt;/upnp:artist&gt;&lt;dc:creator&gt;DJ Shadow&lt;/dc:creator&gt;&lt;upnp:album&gt;Endtroducing.....&lt;/upnp:album&gt;&lt;upnp:albumArtURI&gt;http://10.54.6.186:50002/transcoder/jpegtnscaler.cgi/ebdart/3546.jpg&lt;/upnp:albumArtURI&gt;&lt;dc:date&gt;1996-01-01&lt;/dc:date&gt;&lt;/item&gt;&lt;/DIDL-Lite&gt;"/>
      </InstanceID>
    </Event>

Stepping through [httpsession.cpp](https://github.com/fkuehne/upnpx/blob/9e23c1c1d218e174f403e829f569007e7908c905/src/eventserver/httpsession.cpp), I can see that in the "broken" renderer, the [following code](https://github.com/fkuehne/upnpx/blob/9e23c1c1d218e174f403e829f569007e7908c905/src/eventserver/httpsession.cpp#L86-L90) is not met, therefore it returns as mentioned below.

    // Actual values
    //      1448         ||     3534       |      208
    if(currentFillLength >= mContentlength + mHeaderlength){
        mBody = sessionBuf + mHeaderlength;
        mBodyLen = currentFillLength - mHeaderlength;
        return 0;
    }

    // Returns here instead
    return mContentlength + mHeaderlength - currentFillLength;

**Comment by squarefrog** [comment]
Increasing the buffer in [socketserverconnection.cpp](https://github.com/fkuehne/upnpx/blob/05e0a2f5c27d23ae894db013a6899bce85fed2a4/src/eventserver/socketserverconnection.cpp#L41) seems to fix it. 

    - #define SERVER_BUFFER_STEP 2048
    + #define SERVER_BUFFER_STEP 4096

Do you forsee any issues with this?

**Comment by fkuehne** [comment]
> On 26 Jan 2015, at 13:51, Paul Williamson <notifications@github.com> wrote:
> 
> Increasing the buffer in socketserverconnection.cpp seems to fix it.
> 
> - #define SERVER_BUFFER_STEP 2048
> + #define SERVER_BUFFER_STEP 4096
> 
> Do you forsee any issues with this?

Sorry for the late reply. No, looks fine to me :)
