### ISSUE TITLE
upnpx retrieves incomplete protocol info when browsing.

### ISSUE THREAD

**Issue by squarefrog** [fkuehne/upnpx#48]
When browsing using upnpx I don't get the full protocol info for each track.

### Request Headers

    POST /ContentDirectory/control HTTP/1.1
    Host: 10.54.6.186:50001
    Content-Type: text/xml;charset="utf-8"
    Connection: keep-alive
    SOAPACTION: "urn:schemas-upnp-org:service:ContentDirectory:1#Browse"
    Accept: */*
    User-Agent: iOS UPnP/1.1 UPNPX/1.3.1
    Content-Length: 504
    Accept-Language: en-us
    Accept-Encoding: gzip, deflate

### Request Body

    <?xml version="1.0"?>
    <s:Envelope xmlns:s="http://schemas.xmlsoap.org/soap/envelope/" s:encodingStyle="http://schemas.xmlsoap.org/soap/encoding/">
      <s:Body>
        <u:Browse xmlns:u="urn:schemas-upnp-org:service:ContentDirectory:1">
          <ObjectID>22$299</ObjectID>
          <BrowseFlag>BrowseDirectChildren</BrowseFlag>
          <Filter>*</Filter>
          <StartingIndex>0</StartingIndex>
          <RequestedCount>20</RequestedCount>
          <SortCriteria>+upnp:album,+upnp:originalTrackNumber,+dc:title</SortCriteria>
        </u:Browse>
      </s:Body>
    </s:Envelope>
    
### Response

    <?xml version="1.0"?>
    <DIDL-Lite xmlns="urn:schemas-upnp-org:metadata-1-0/DIDL-Lite/" xmlns:dc="http://purl.org/dc/elements/1.1/" xmlns:upnp="urn:schemas-upnp-org:metadata-1-0/upnp/" xmlns:sec="http://www.sec.co.kr/" xmlns:dlna="urn:schemas-dlna-org:metadata-1-0/">
      <item id="22$@9017" parentID="22$299" restricted="1">
        <dc:title>What Do You Do For Money Honey</dc:title>
        <upnp:class>object.item.audioItem.musicTrack</upnp:class>
        <dc:date>2009-01-01</dc:date>
        <upnp:album>Greatest Hell's Hits (Disc 1)</upnp:album>
        <upnp:albumArtist>AC/DC</upnp:albumArtist>
        <upnp:artist>ACDC</upnp:artist>
        <dc:creator>ACDC</dc:creator>
        <upnp:genre>Rock</upnp:genre>
        <upnp:originalTrackNumber>13</upnp:originalTrackNumber>
        <upnp:albumArtURI dlna:profileID="JPEG_TN">http://10.54.6.186:50002/transcoder/jpegtnscaler.cgi/ebdart/9017.jpg</upnp:albumArtURI>
        <res protocolInfo="http-get:*:audio/x-flac:*" size="27745455" bitrate="127500" duration="0:03:37.000" nrAudioChannels="2" sampleFrequency="44100">http://10.54.6.186:50002/m/NDLNA/9017.flac</res>
      </item>
    
    ///// .....
    
    </DIDL-Lite>

### Request Headers

    POST /ContentDirectory/control HTTP/1.1
    Content-type: text/xml;charset="utf-8"
    Soapaction: "urn:schemas-upnp-org:service:ContentDirectory:1#Browse"
    Content-Length: 474
    Host: 10.54.6.186:50001
    Connection: Keep-Alive
    User-Agent: Android/4.4.3 UPnP/1.0 BubbleUPnP/2.3.1

### Request Body

    <?xml version="1.0"?>
    <s:Envelope xmlns:s="http://schemas.xmlsoap.org/soap/envelope/" s:encodingStyle="http://schemas.xmlsoap.org/soap/encoding/">
      <s:Body>
        <u:Browse xmlns:u="urn:schemas-upnp-org:service:ContentDirectory:1">
          <ObjectID>22$299</ObjectID>
          <BrowseFlag>BrowseDirectChildren</BrowseFlag>
          <Filter>*</Filter>
          <StartingIndex>0</StartingIndex>
          <RequestedCount>16</RequestedCount>
          <SortCriteria/>
        </u:Browse>
      </s:Body>
    </s:Envelope>

### Response

    <?xml version="1.0"?>
    <DIDL-Lite xmlns="urn:schemas-upnp-org:metadata-1-0/DIDL-Lite/" xmlns:dc="http://purl.org/dc/elements/1.1/" xmlns:upnp="urn:schemas-upnp-org:metadata-1-0/upnp/" xmlns:sec="http://www.sec.co.kr/" xmlns:dlna="urn:schemas-dlna-org:metadata-1-0/">
      <item id="22$@9005" parentID="22$299" restricted="1">
        <dc:title>What Do You Do For Money Honey</dc:title>
        <upnp:class>object.item.audioItem.musicTrack</upnp:class>
        <dc:date>2009-01-01</dc:date>
        <upnp:album>Greatest Hell's Hits (Disc 1)</upnp:album>
        <upnp:albumArtist>AC/DC</upnp:albumArtist>
        <upnp:artist>ACDC</upnp:artist>
        <dc:creator>ACDC</dc:creator>
        <upnp:genre>Rock</upnp:genre>
        <upnp:originalTrackNumber>13</upnp:originalTrackNumber>
        <upnp:albumArtURI dlna:profileID="JPEG_TN">http://10.54.6.186:50002/transcoder/jpegtnscaler.cgi/ebdart/9017.jpg</upnp:albumArtURI>
        <res protocolInfo="http-get:*:audio/x-flac:DLNA.ORG_OP=01;DLNA.ORG_FLAGS=01700000000000000000000000000000" size="27745455" bitrate="127500" duration="0:03:37.000" nrAudioChannels="2" sampleFrequency="44100">http://10.54.6.186:50002/m/NDLNA/9017.flac</res>
      </item>
    
    ///// .....
    
    </DIDL-Lite>

Looking at the `<res protocolInfo>` property you can clearly see the differences.

#### upnpx

    http-get:*:audio/x-flac:*

#### BubbleUPnP

    http-get:*:audio/x-flac:DLNA.ORG_OP=01;DLNA.ORG_FLAGS=01700000000000000000000000000000

### Why is this an issue?

Without setting the flags, the renderer has no idea that the server is capable of supporting file resuming. You can read more on the flags and what they mean [here](http://libdlna.sourcearchive.com/documentation/0.2.3/dlna_8h-source.html).

**Comment by squarefrog** [comment]
OK. This is very strange. If you override the `User-Agent` header to be:

    User-Agent: Android/4.4.3 UPnP/1.1 UPNPX/1.3.1

Then protocol info is properly returned.

**Comment by lightbow** [comment]
I wonder if it's the number of slashes. Can you try it with "iOS/8.1 UPnP/1.1 UPNPX/1.3.1"?

**Comment by squarefrog** [comment]
If you change it from anything other than `Android` it fails to return the protocol info.

My guess is this is a quirk with the server I am using (Synology Diskstation DS214SE). I know UPnP devices are supposed to parse the contents of the `User-Agent` header, but I don't know if they are supposed to have playable profiles.

I've only experienced this issue with FLAC content.

**Comment by squarefrog** [comment]
In further testing, it definitely seems like a server specific bug. I'm going to close this issue but leave my findings here in case they prove useful for someone else.

### Synology upnp module (nupnp?)

Will only send the extended protocol info when `User-Agent` contains Android with FLAC format.

### Twonky

Never seems to send the extended protocol info with FLAC format

### Minidlna

Never seems to send the extended protocol info with FLAC format

---

As this seems like a server specific bug, I'm going to close this issue, as I believe it should be handled in your app. In my case, when preparing the metadata to send to a renderer I'm going to force the flags. I can do this as I only have to support a limited number of renderers, but you may want to proceed with more caution.

    NSString *flags = @"DLNA.ORG_FLAGS";
    NSString *newProtocol = self.protocolInfo;

    if (![newProtocol containsString:flags]) {
        
        // http-get:*:audio/x-flac:*
        // http-get:*:audio/x-flac:DLNA.ORG_OP=01;DLNA.ORG_FLAGS=01700000000000000000000000000000

        // Check if last char *
        NSString *lastChar;
        NSUInteger length = newProtocol.length;
        lastChar = [newProtocol substringFromIndex:length - 1];
        
        if ([lastChar isEqualToString:@"*"]) {
            newProtocol = [newProtocol substringToIndex:length - 1];
        }
        
        flags = @"DLNA.ORG_FLAGS=01700000000000000000000000000000";
        newProtocol = [newProtocol stringByAppendingString:flags];
        
    }

    /* DLNA.ORG_OP: operations parameter (string)
     *     "00" (or "0") neither time seek range nor range supported
     *     "01" range supported
     *     "10" time seek range supported
     *     "11" both time seek range and range supported
     */
    flags = @"DLNA.ORG_OP";
    if (![newProtocol containsString:flags]) {
        flags = @";DLNA.ORG_OP=01";
        newProtocol = [newProtocol stringByAppendingString:flags];
    }

    [metadata appendFormat:@"protocolInfo=\"%@\" ", newProtocol];

#### Warning:

'Hacking' the metadata like this is not necessarily safe. If your server does not support streaming transfer mode, then this will make your renderer think it supports pause/resume when it actually doesn't.
