### ISSUE TITLE
ssdp.cpp crashes with SIGPIPE when returning from background

### ISSUE THREAD

**Issue by squarefrog** [fkuehne/upnpx#52]
I have allowed my app to run in the background, which works fine. I do however experience a `SIGPIPE` call when returning.

## Steps to reproduce

* Play some music
* Move into the background
* After the last track stops, wait 5 minutes
* Open the app up again
* Go back to the root view controller, where `[[manager SSDP] searchSSDP];` is called in `viewWillAppear:`
* App crashes on [line 431[(https://github.com/fkuehne/upnpx/blob/master/src/ssdp/ssdp.cpp#L431).

I understand this issue is related to writing to a broken socket. I am unable to stop the SSDP server, as I observing UPnP events (transport changes etc.)

I believe this may be a simple fix of ignoring `SIGPIPE` exceptions, based on [this stackoverflow answer](http://stackoverflow.com/questions/5714162/sigpipe-crash-when-switching-background-task/6209056#6209056). I'm going to test this this morning and submit a PR.

@fkuehne feel free to raise any concerns about this in this discussion.

**Comment by rworne** [comment]
Is this after 5 minutes, or after 10 minutes?  iOS will kill background network connections after 10 minutes.  My previous UPNP framework had this issue too, and I think I had SO_NOSIGPIPE in setsockopt to fix it.

**Comment by squarefrog** [comment]
It can happen after a couple of minutes but way before the 10 minute timeout. 

The attached pull request fixes it well, with no immediately apparent side effects.

**Comment by fkuehne** [comment]
Merged, thanks for you work!
