### ISSUE TITLE
iOS 9 / Xcode 7 Bitcode compatibility

### ISSUE THREAD

**Issue by oemera** [fkuehne/upnpx#67]
Yesterday the GM for iOS 9 was released and we tried to build our app with the current setup and dependencies with Xcode 7 to make sure everything works. It turns out we have a couple of pods which don't work well with Bitcode. One of them is upnpx.

When you try to build a app with Xcode 7 which includes the upnpx pod it will fail with the following error <code>ld: -weak_library and -bitcode_bundle (Xcode setting ENABLE_BITCODE=YES) cannot be used together
clang: error: linker command failed with exit code 1 (use -v to see invocation)</code>

Are you planing to fix this issue?

**Comment by sylverb** [comment]
the pod spec file should be updated to add : 
> s.libraries = 'c++'
and this line should be removed : 
> 'OTHER_LDFLAGS' => '-weak_library /usr/lib/libstdc++.dylib'
