### ISSUE TITLE
Cleartext HTTP (http://) resource load since it is insecure

### ISSUE THREAD

**Issue by plashchynski** [fkuehne/upnpx#70]
There is an worning on new XCode 7 and iOS 9.2:

```
App Transport Security has blocked a cleartext HTTP (http://) resource load since it is insecure. Temporary exceptions can be configured via your app's Info.plist file.
```

It shows like a warning, but it causes that the rootDevices array is always empty.

It's due to a new security restrictions about HTTP https://developer.apple.com/videos/play/wwdc2015-711/

A possible solution is to add an exception (just like described in the message) to Info.plist file; however, maybe there's a permanent solution?

**Comment by fkuehne** [comment]
There is no permanent solution as of yet except for adding an exception to the Info.plist file as upnpx needs to access all local http servers it finds.

As far as I know, there is not currently no way to white-list all IP ranges designated to local networks, which would be the correct way to go as UPnP can't go beyond those ranges anyway (unless you are using public IPs on your LAN, which is a bad idea).
