### ISSUE TITLE
36 crashes from 8 users on line 211 of SSDPParser::ReadLine

### ISSUE THREAD

**Issue by xaphod** [fkuehne/upnpx#91]
Hi there,
I'm seeing more and more crashes on line 211 of SSDPParser::ReadLine, the while-loop condition below:

`int SSDPParser::ReadLine(u8 *buf, u32 len, u8 **restbuf, u32 *restlen){
    int ret = 0;

    //Search the \r\n
    u8 *pos = buf;
    while((pos < (u8*)(buf+(len-1)) ) && (*pos != '\r' && *(pos+1) != '\n')){
        pos++;
    }
`

Any idea what this could be, maybe a NULL where one isn't expected? Any way to make this safer?

**Comment by xaphod** [comment]
Looks like this is fixed in two commits, starting from this one: https://github.com/dmappgroup/upnpx/commit/9923ce2b9bd86cd7d2c62d27f7221e35f4e77d1b

**Comment by xaphod** [comment]
Oops, no, I still see crashes in thew wild with that fix from dmappgroup :(

**Comment by xaphod** [comment]
New attempted fix for this issue is in eoe20cd: https://github.com/xaphod/upnpx/commit/e0e20cd0d0e787075c1cb93f9545464425a0a2ba

**Comment by mgatelabs** [comment]
I've had my users look for the cause of crashes and it looks like a recent Harmony Hub update is causing it to send out weird responses.

**Comment by xaphod** [comment]
@mgatelabs It's because any SSDP response that does not have a proper \r\n\r\n termination will crash the SSDPParser. Possibly this is what happens. Also if packet fragmentation happens and a short message arrives (ie. a single byte), it'll also crash in SSDPParser.
My fork is up to date as of 1 hour ago with the latest commit https://github.com/xaphod/upnpx/commit/bd79b0a1f8e4dda5e0eb544e4d5eb56f8393bc15
Pretty sure I finally nailed this bug.

**Comment by mgatelabs** [comment]
I may have the fix, i've applied everyone else's fixes, but also added a null check to the first if condition about length < 2.  One user says it's working.  I'll post up the details later when I get back to my rig.

**Comment by xaphod** [comment]
@mgatelabs Yes i added the length < 2 check a while back in my branch also

**Comment by fkuehne** [comment]
A pull request would be highly welcome 🙂🙃🙂

**Comment by xaphod** [comment]
OK the fix looks good, lots of time for users to have hit this, and no one appears to have yet.
Pull request 92 created, modifies only 1 file: https://github.com/fkuehne/upnpx/pull/92/files

**Comment by xaphod** [comment]
Pull request was merged in today, #92
